name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Configure Git
        run: |
          git config --global user.email "liaqatsaeed007@gmail.com"
          git config --global user.name "Liaqat Saeed"

      - name: Build package
        run: pnpm run build

      - name: Bump version and generate changelog
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}